apiVersion: v1
kind: Pod
metadata:
  name: hello-x86
spec:
  containers:
  - name: hello
    image: public.ecr.aws/eks-distro-build-tooling/eks-distro-minimal-base-nginx:latest
  nodeSelector:
    kubernetes.io/arch: amd64
